version: '2.3'

services:
  mongo:
    image: mongo:2.6
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    restart: always
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
        interval: 30s
        timeout: 10s
        retries: 5

  # web:
  #   build: .
  #   command: 'sh -c scripts/docker-up.sh'
  #   restart: always
  #   depends_on:
  #     search:
  #       condition: service_healthy
  #   ports:
  #     - 3333:3000
  #   environment:
  #     S3_BUCKET_NAME:
  #     S3_ACCESS_KEY:
  #     S3_SECRET_KEY:
  #     SERVER_S3_ACCESS_KEY:
  #     SERVER_S3_SECRET_KEY:
  #     ALERTS:
  #     SECRET_KEY_BASE: '0ccd94b250496de9a5765981b0703279bc4ece38c6213a81a3dd8fe215dc51d4c7eee05f49370b010ecf62109e201f935536496ec661a759118ebb011420060a'
  #     MONGO_HOST: mongo
  #     ELASTICSEARCH_URL: 'http://search:9200'
  #     RAILS_ENV: development
  #     RACK_ENV: development

volumes:
  mongodata:
  esdata:
